logging.level.org.zalando.logbook: INFO

spring:
  sql:
    init.mode: always

  datasource:
    url: jdbc:h2:file:./db/filmorate
    username: sa
    password: password
    driverClassName: org.h2.Driver

  h2:
    # после запуска приложения, можно перейти к http://localhost:8080/h2-console, который представит страницу входа.
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
