DROP TABLE IF EXISTS users, films, genres, film_genre, film_rating_mpa, users_likes_films, user_friends CASCADE;

CREATE TABLE users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(100) NOT NULL,
    login VARCHAR(100) NOT NULL UNIQUE,
    name VARCHAR(100),
    birthday DATE
);

CREATE TABLE films (
    film_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(1000),
    release_date DATE,
    duration INTEGER,
    mpa_id INTEGER
);

CREATE TABLE genres (
    genre_id INTEGER NOT NULL PRIMARY KEY,
    genre_name varchar
);

CREATE TABLE film_genre (
    film_id BIGINT NOT NULL REFERENCES films(film_id) ON DELETE CASCADE,
    genre_id INTEGER NOT NULL REFERENCES genres(genre_id) ON DELETE CASCADE
);

CREATE TABLE film_rating_mpa (
    mpa_id INTEGER NOT NULL PRIMARY KEY,
    mpa_name varchar
);

CREATE TABLE users_likes_films (
    film_id BIGINT,
    user_id BIGINT,
    FOREIGN KEY (film_id) REFERENCES films(film_id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE TABLE user_friends (
    user_id BIGINT NOT NULL,
    friend_id BIGINT NOT NULL,
    status ENUM('UNCONFIRMED', 'CONFIRMED'),
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    FOREIGN KEY (friend_id) REFERENCES users(user_id) ON DELETE CASCADE
);
